### ISSUE TITLE
 Hey, from Devpost. #1 

### ISSUE THREAD

**Issue by NitkarshChourasia** [kira-kaur-sidhu/jasmine-kim-kira-sarah-chess-engine#1]
As you are working solo.
I am looking for a partner to work with for the upcoming Hackathon submission.
Are you willing to pair up?
There wasn't other way to message you, So...

**Comment by kira-kaur-sidhu** [comment]
What hackathon are you interested in working on?

**Comment by NitkarshChourasia** [comment]
Dear kira-kaur-sidhu,

Thank you for reaching out to me. I saw your project, [quterus](https://github.com/kira-kaur-sidhu/quterus), and I must say, I liked it. Winning hackathons is not my main goal; what interests me most is the journey of learning and improving my skills. Participating in a hackathon can make the learning process more enjoyable and teach valuable soft skills, especially teamwork.

As of now, I don't have a specific hackathon in mind, but I find that our interests align, and I believe we could make great coding buddies. Having a partner helps with accountability and allows for learning from each other. Plus, it develops essential soft skills like empathy and communication.

Currently, I am focusing on various skills such as Python, JavaScript, Machine Learning, Data/Big Data, C++, Front-end and Back-end development, and learning the fundamentals of Computer Science. Additionally, I am working on Data Structures and Algorithms with Python and exploring Django and Linux.

I believe that taking up pragmatic projects, like your impressive quterus, is an efficient way to become proficient. My uniqueness lies in out-of-the-box thinking and coming up with unique ideas and solutions.

I look forward to the opportunity to work with you on any project you choose. The experience of collaborating with someone like you, who shares similar interests, would be truly enriching.

Best regards,
NitkarshChourasia

**Comment by NitkarshChourasia** [comment]
At least close it, didi.
